id = "gram"
name = "Gram Language Support"
version = "0.2.7"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - a subject-oriented notation for structured data"

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "https://github.com/gram-data/tree-sitter-gram"
rev = "b439325292d8ddbe4d739a76079f1842d62a1807"
