id = "gram"
name = "Gram Language Support"
version = "0.2.5"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - a subject-oriented notation for structured data"

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "https://github.com/gram-data/tree-sitter-gram"
rev = "84ec592d27a13267097d83e94932de3e024ea808"
